require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/topics', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Topic. As you add validations to Topic, be sure to
  # adjust the attributes here as well.
  let(:author) { FactoryBot.create(:author) }
  let(:tag) { FactoryBot.create(:tag) }

  let(:valid_attributes) do
    { title: Faker::Lorem.word, description: Faker::Lorem.sentence, tag_id: tag.id }
  end

  let(:invalid_attributes) do
    { title: '', description: '', tag_id: nil }
  end

  before(:each) do
    sign_in author
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Topic.create! valid_attributes
      get topics_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      topic = Topic.create! valid_attributes
      get topic_url(topic)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_topic_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      topic = Topic.create! valid_attributes
      get edit_topic_url(topic)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Topic' do
        expect do
          post topics_url, params: { topic: valid_attributes }
        end.to change(Topic, :count).by(1)
      end

      it 'redirects to the created topic' do
        post topics_url, params: { topic: valid_attributes }
        expect(response).to redirect_to(topic_url(Topic.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Topic' do
        expect do
          post topics_url, params: { topic: invalid_attributes }
        end.to change(Topic, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post topics_url, params: { topic: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        { title: Faker::Lorem.word, description: Faker::Lorem.sentence, tag_id: tag.id }
      end

      it 'updates the requested topic' do
        topic = Topic.create! valid_attributes
        patch topic_url(topic), params: { topic: new_attributes }
        topic.reload
        expect(topic.title).to eq(new_attributes[:title])
        expect(topic.description).to eq(new_attributes[:description])
        expect(topic.tag_id).to eq(new_attributes[:tag_id])
      end

      it 'redirects to the topic' do
        topic = Topic.create! valid_attributes
        patch topic_url(topic), params: { topic: new_attributes }
        topic.reload
        expect(response).to redirect_to(topic_url(topic))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        topic = Topic.create! valid_attributes
        patch topic_url(topic), params: { topic: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested topic' do
      topic = Topic.create! valid_attributes
      expect do
        delete topic_url(topic)
      end.to change(Topic, :count).by(-1)
    end

    it 'redirects to the topics list' do
      topic = Topic.create! valid_attributes
      delete topic_url(topic)
      expect(response).to redirect_to(topics_url)
    end
  end
end
